import type { SeedAsset } from "@/contentful/seed/helpers";

export const assetSeeds: SeedAsset[] = [
  {
    id: "asset_hero_home_dawn_desktop",
    title: "Home hero dawn desktop",
    description: "Warm editorial scene with candlelight and folded linen.",
    path: "/placeholders/hero-home-dawn-desktop.svg",
    width: 1600,
    height: 1080,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_hero_home_dawn_mobile",
    title: "Home hero dawn mobile",
    description: "Mobile crop of the dawn home hero.",
    path: "/placeholders/hero-home-dawn-mobile.svg",
    width: 900,
    height: 1200,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_hero_home_gifting_desktop",
    title: "Home hero gifting desktop",
    description: "Giftable premium arrangement in warm seasonal light.",
    path: "/placeholders/hero-home-gifting-desktop.svg",
    width: 1600,
    height: 1080,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_hero_home_gifting_mobile",
    title: "Home hero gifting mobile",
    description: "Mobile crop of the gifting hero.",
    path: "/placeholders/hero-home-gifting-mobile.svg",
    width: 900,
    height: 1200,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_hero_home_ritual_desktop",
    title: "Home hero ritual desktop",
    description: "Editorial self-care arrangement with steam and stone textures.",
    path: "/placeholders/hero-home-ritual-desktop.svg",
    width: 1600,
    height: 1080,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_hero_home_ritual_mobile",
    title: "Home hero ritual mobile",
    description: "Mobile crop of the ritual hero.",
    path: "/placeholders/hero-home-ritual-mobile.svg",
    width: 900,
    height: 1200,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_hero_campaign_black_friday",
    title: "Black Friday campaign hero",
    description: "Seasonal campaign image with soft shadow and premium product styling.",
    path: "/placeholders/hero-campaign-black-friday.svg",
    width: 1600,
    height: 1080,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_hero_campaign_cyber_monday",
    title: "Cyber Monday campaign hero",
    description: "Refined deep-toned campaign image for late-night offer.",
    path: "/placeholders/hero-campaign-cyber-monday.svg",
    width: 1600,
    height: 1080,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_category_home_fragrance",
    title: "Home fragrance category",
    description: "Still life featuring diffusers, candles, and polished stone.",
    path: "/placeholders/category-home-fragrance.svg",
    width: 900,
    height: 1100,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_category_bath_shower",
    title: "Bath and shower category",
    description: "Steam-lit shower ritual placeholder image.",
    path: "/placeholders/category-bath-shower.svg",
    width: 900,
    height: 1100,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_category_body_hand",
    title: "Body and hand care category",
    description: "Rich cream textures and softened shadows.",
    path: "/placeholders/category-body-hand.svg",
    width: 900,
    height: 1100,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_category_gift_sets",
    title: "Gift sets category",
    description: "Premium boxed gift presentation with ribbon and card.",
    path: "/placeholders/category-gift-sets.svg",
    width: 900,
    height: 1100,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_category_wellness_accessories",
    title: "Wellness accessories category",
    description: "Stone tray, sleep tools, and resting textiles.",
    path: "/placeholders/category-wellness-accessories.svg",
    width: 900,
    height: 1100,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_product_set_a",
    title: "Product set A",
    description: "Neutral candle and room fragrance composition.",
    path: "/placeholders/product-set-a.svg",
    width: 1000,
    height: 1250,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_product_set_b",
    title: "Product set B",
    description: "Warm shower and bath collection composition.",
    path: "/placeholders/product-set-b.svg",
    width: 1000,
    height: 1250,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_product_set_c",
    title: "Product set C",
    description: "Giftable body care arrangement composition.",
    path: "/placeholders/product-set-c.svg",
    width: 1000,
    height: 1250,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_product_set_d",
    title: "Product set D",
    description: "Accessory and sleep ritual composition.",
    path: "/placeholders/product-set-d.svg",
    width: 1000,
    height: 1250,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_story_founders",
    title: "Brand story founders image",
    description: "Editorial founder narrative image with calm interior styling.",
    path: "/placeholders/story-founders.svg",
    width: 1500,
    height: 1050,
    contentType: "image/svg+xml",
  },
  {
    id: "asset_story_craft",
    title: "Brand story craft image",
    description: "Product making and packaging details in warm light.",
    path: "/placeholders/story-craft.svg",
    width: 1500,
    height: 1050,
    contentType: "image/svg+xml",
  },
];
