import { richTextParagraphs } from "@/contentful/seed/helpers";
import type {
  SeedCampaign,
  SeedCategory,
  SeedHeroBanner,
  SeedProduct,
  SeedPromoStrip,
} from "@/contentful/seed/helpers";

export const categorySeeds: SeedCategory[] = [
  {
    id: "category_home_fragrance",
    internalName: "Category: Home Fragrance",
    slug: "home-fragrance",
    title: "Home Fragrance",
    description:
      "Candlelight, diffusers, and room mists that soften the atmosphere from morning to evening.",
    imageId: "asset_category_home_fragrance",
  },
  {
    id: "category_bath_shower",
    internalName: "Category: Bath & Shower",
    slug: "bath-shower",
    title: "Bath & Shower",
    description:
      "Elevated shower foams and soaks designed to turn everyday moments into a gentler reset.",
    imageId: "asset_category_bath_shower",
  },
  {
    id: "category_body_hand_care",
    internalName: "Category: Body & Hand Care",
    slug: "body-hand-care",
    title: "Body & Hand Care",
    description:
      "Comforting creams, balms, and washes with polished textures and quietly modern scent profiles.",
    imageId: "asset_category_body_hand",
  },
  {
    id: "category_gift_sets",
    internalName: "Category: Gift Sets",
    slug: "gift-sets",
    title: "Gift Sets",
    description:
      "Ready-to-give collections assembled around the feeling of ease, light, and homecoming.",
    imageId: "asset_category_gift_sets",
  },
  {
    id: "category_wellness_accessories",
    internalName: "Category: Wellness Accessories",
    slug: "wellness-accessories",
    title: "Wellness Accessories",
    description:
      "Small ritual tools for bedside calm, slower mornings, and restorative evening routines.",
    imageId: "asset_category_wellness_accessories",
  },
];

export const heroBannerSeeds: SeedHeroBanner[] = [
  {
    id: "hero_home_relax",
    internalName: "Home Hero: Relax & Unwind",
    eyebrow: "Serein House",
    headline: "Quiet rituals for luminous days.",
    subheadline:
      "Build a softer pace with mineral soaks, cedar warmth, and rooms that feel gently held.",
    ctaLabel: "Shop the quiet edit",
    ctaHref: "/deals",
    desktopImageId: "asset_hero_home_dawn_desktop",
    mobileImageId: "asset_hero_home_dawn_mobile",
    theme: "linen",
    audienceSegments: ["relax-and-unwind"],
  },
  {
    id: "hero_home_gifting",
    internalName: "Home Hero: Gifting",
    eyebrow: "Seasonal Giving",
    headline: "Give beautifully, with calm built in.",
    subheadline:
      "Refined gift boxes, warm fragrance, and polished rituals designed to feel personal from the first glance.",
    ctaLabel: "Discover gift sets",
    ctaHref: "/deals",
    desktopImageId: "asset_hero_home_gifting_desktop",
    mobileImageId: "asset_hero_home_gifting_mobile",
    theme: "clay",
    audienceSegments: ["gifting"],
    draftOverrides: {
      headline: "Give beautifully, before the season rush begins.",
      subheadline:
        "Preview a quieter gifting mood with early access bundles, polished wrapping moments, and generous offer storytelling.",
    },
  },
  {
    id: "hero_home_self_care",
    internalName: "Home Hero: Self Care Ritual",
    eyebrow: "Daily Renewal",
    headline: "Shape the day around one unrushed moment.",
    subheadline:
      "Foaming showers, body creme, and bedside essentials for a ritual that begins with attention and ends in ease.",
    ctaLabel: "Start your ritual",
    ctaHref: "/deals",
    desktopImageId: "asset_hero_home_ritual_desktop",
    mobileImageId: "asset_hero_home_ritual_mobile",
    theme: "sage",
    audienceSegments: ["self-care-ritual"],
  },
  {
    id: "hero_campaign_teaser",
    internalName: "Campaign Hero: First Light Preview",
    eyebrow: "Pre-Black-Friday Teaser",
    headline: "The season opens in a softer key.",
    subheadline:
      "A first look at quiet gifting, warming fragrance, and limited seasonal sets before the full event begins.",
    ctaLabel: "Preview the edit",
    ctaHref: "/deals",
    desktopImageId: "asset_hero_home_gifting_desktop",
    mobileImageId: "asset_hero_home_gifting_mobile",
    theme: "mist",
    campaignId: "campaign_first_light_preview",
    audienceSegments: [],
  },
  {
    id: "hero_campaign_black_friday",
    internalName: "Campaign Hero: Velvet Friday Event",
    eyebrow: "Black Friday",
    headline: "The Velvet Friday Event has arrived.",
    subheadline:
      "Elevated sets, seasonal savings, and best-loved rituals gathered into one polished weekend collection.",
    ctaLabel: "Shop the event",
    ctaHref: "/deals",
    desktopImageId: "asset_hero_campaign_black_friday",
    mobileImageId: "asset_hero_home_gifting_mobile",
    theme: "charcoal",
    campaignId: "campaign_velvet_friday_event",
    audienceSegments: [],
  },
  {
    id: "hero_campaign_weekend",
    internalName: "Campaign Hero: Quiet Weekend Extension",
    eyebrow: "Weekend Extension",
    headline: "A little more time for the pieces you loved most.",
    subheadline:
      "The weekend remains open with select bundles, layered fragrance, and gifting essentials still in the spotlight.",
    ctaLabel: "Continue shopping",
    ctaHref: "/deals",
    desktopImageId: "asset_hero_campaign_black_friday",
    mobileImageId: "asset_hero_home_dawn_mobile",
    theme: "clay",
    campaignId: "campaign_quiet_weekend_extension",
    audienceSegments: [],
  },
  {
    id: "hero_campaign_cyber_monday",
    internalName: "Campaign Hero: Midnight Monday Finale",
    eyebrow: "Cyber Monday",
    headline: "The finale shifts into a deeper glow.",
    subheadline:
      "A focused final day of online-only offers, pared-back selections, and one last invitation to gift well.",
    ctaLabel: "See final offers",
    ctaHref: "/deals",
    desktopImageId: "asset_hero_campaign_cyber_monday",
    mobileImageId: "asset_hero_home_ritual_mobile",
    theme: "charcoal",
    campaignId: "campaign_midnight_monday_finale",
    audienceSegments: [],
  },
];

export const promoStripSeeds: SeedPromoStrip[] = [
  {
    id: "promo_global_default",
    internalName: "Promo Strip: Default",
    message: "Complimentary gift wrap on curated sets over $85.",
    ctaLabel: "Explore gift sets",
    ctaHref: "/deals",
    theme: "linen",
    audienceSegments: [],
  },
  {
    id: "promo_teaser_all",
    internalName: "Promo Strip: Teaser",
    message: "Early access preview now open. Seasonal sets arrive first for the quietly curious.",
    ctaLabel: "Preview the campaign",
    ctaHref: "/deals",
    theme: "mist",
    campaignId: "campaign_first_light_preview",
    audienceSegments: [],
  },
  {
    id: "promo_bf_gifting",
    internalName: "Promo Strip: Black Friday Gifting",
    message: "Gift boxes and hand rituals now begin at $58 for a limited holiday window.",
    ctaLabel: "Shop gifting",
    ctaHref: "/deals",
    theme: "clay",
    campaignId: "campaign_velvet_friday_event",
    audienceSegments: ["gifting"],
    draftOverrides: {
      message: "Gift boxes and polished hand rituals now begin at $54 while the preview revision is in draft.",
    },
  },
  {
    id: "promo_bf_relax",
    internalName: "Promo Strip: Black Friday Relax",
    message: "Save on candles, diffusers, and room mists chosen for slower evenings at home.",
    ctaLabel: "Shop home fragrance",
    ctaHref: "/deals",
    theme: "charcoal",
    campaignId: "campaign_velvet_friday_event",
    audienceSegments: ["relax-and-unwind"],
  },
  {
    id: "promo_weekend_all",
    internalName: "Promo Strip: Weekend Extension",
    message: "Weekend extension now live. Select bestsellers remain in the event through Sunday night.",
    ctaLabel: "See remaining offers",
    ctaHref: "/deals",
    theme: "sage",
    campaignId: "campaign_quiet_weekend_extension",
    audienceSegments: [],
  },
  {
    id: "promo_cyber_all",
    internalName: "Promo Strip: Cyber Monday",
    message: "Final online-only pricing now available until midnight on curated favorites.",
    ctaLabel: "View final picks",
    ctaHref: "/deals",
    theme: "charcoal",
    campaignId: "campaign_midnight_monday_finale",
    audienceSegments: [],
  },
];

export const productSeeds: SeedProduct[] = [
  {
    id: "product_dawn_ember_candle",
    internalName: "Product: Dawn Ember Candle",
    slug: "dawn-ember-candle",
    name: "Dawn Ember Candle",
    shortDescription: "A soft mineral candle with cedarwood, iris, and warmed resin.",
    longDescription: richTextParagraphs(
      "Dawn Ember opens with a clean mineral brightness before settling into cedarwood, powdered iris, and a low amber warmth that lingers beautifully through the evening.",
      "Designed for entry tables, bedside rituals, and slower weekend rooms, it casts a steady glow without overwhelming the atmosphere.",
    ),
    price: 52,
    salePrice: 44,
    sku: "SH-HF-101",
    primaryImageId: "asset_product_set_a",
    galleryImageIds: ["asset_product_set_a", "asset_hero_home_dawn_desktop"],
    categoryId: "category_home_fragrance",
    tags: ["cedar", "amber", "candle"],
    audienceSegments: ["relax-and-unwind", "gifting"],
    featuredCampaignIds: ["campaign_velvet_friday_event", "campaign_first_light_preview"],
    badgeText: "Best Seller",
    specs: {
      burnTime: "50 hours",
      vessel: "Tinted glass",
      wax: "Coconut-soy blend",
      mood: ["warm", "grounded", "quiet"],
    },
    seoTitle: "Dawn Ember Candle | Serein House",
    seoDescription: "A premium mineral candle with cedarwood, iris, and amber warmth.",
  },
  {
    id: "product_quiet_cedar_diffuser",
    internalName: "Product: Quiet Cedar Diffuser",
    slug: "quiet-cedar-diffuser",
    name: "Quiet Cedar Diffuser",
    shortDescription: "A long-lasting diffuser with cedar, bergamot peel, and cashmere musk.",
    longDescription: richTextParagraphs(
      "Quiet Cedar is made for rooms where you want atmosphere without effort. The scent unfolds slowly, with dry woods and softened citrus that read polished rather than sharp.",
      "Place it in a living room, dressing area, or hallway for a constant sense of calm presence.",
    ),
    price: 68,
    salePrice: 58,
    sku: "SH-HF-102",
    primaryImageId: "asset_product_set_a",
    galleryImageIds: ["asset_product_set_a", "asset_category_home_fragrance"],
    categoryId: "category_home_fragrance",
    tags: ["cedar", "diffuser", "bergamot"],
    audienceSegments: ["relax-and-unwind"],
    featuredCampaignIds: ["campaign_velvet_friday_event", "campaign_quiet_weekend_extension"],
    badgeText: "Seasonal Pick",
    specs: {
      duration: "10-12 weeks",
      reeds: "Natural fiber",
      volume: "250 ml",
    },
    seoTitle: "Quiet Cedar Diffuser | Serein House",
    seoDescription: "A premium reed diffuser with cedar, bergamot peel, and cashmere musk.",
  },
  {
    id: "product_neroli_veil_room_mist",
    internalName: "Product: Neroli Veil Room Mist",
    slug: "neroli-veil-room-mist",
    name: "Neroli Veil Room Mist",
    shortDescription: "A bright room spray with neroli blossom, white tea, and pale woods.",
    longDescription: richTextParagraphs(
      "Neroli Veil clears the air with a lifted opening of blossom and tea before settling into pale woods that soften fabrics, hallways, and guest spaces.",
      "It is especially suited to gifting thanks to its universally elegant profile.",
    ),
    price: 34,
    salePrice: 29,
    sku: "SH-HF-103",
    primaryImageId: "asset_product_set_a",
    galleryImageIds: ["asset_product_set_a", "asset_category_home_fragrance"],
    categoryId: "category_home_fragrance",
    tags: ["neroli", "mist", "giftable"],
    audienceSegments: ["gifting", "self-care-ritual"],
    featuredCampaignIds: ["campaign_first_light_preview", "campaign_midnight_monday_finale"],
    badgeText: "Gift Favorite",
    specs: {
      volume: "100 ml",
      finish: "Fine continuous mist",
      mood: ["bright", "clean", "welcoming"],
    },
    seoTitle: "Neroli Veil Room Mist | Serein House",
    seoDescription: "A premium room mist with neroli blossom, white tea, and pale woods.",
  },
  {
    id: "product_silk_mineral_shower_foam",
    internalName: "Product: Silk Mineral Shower Foam",
    slug: "silk-mineral-shower-foam",
    name: "Silk Mineral Shower Foam",
    shortDescription: "A dense foaming shower gel with white fig and mineral water notes.",
    longDescription: richTextParagraphs(
      "Silk Mineral blooms into a cushioned foam the moment it meets water, wrapping the skin in a fresh fig softness that feels polished and restorative.",
      "It is ideal for daily use when you want the shower to feel considered without becoming complicated.",
    ),
    price: 24,
    salePrice: 19,
    sku: "SH-BS-201",
    primaryImageId: "asset_product_set_b",
    galleryImageIds: ["asset_product_set_b", "asset_category_bath_shower"],
    categoryId: "category_bath_shower",
    tags: ["shower", "fig", "foam"],
    audienceSegments: ["self-care-ritual"],
    featuredCampaignIds: ["campaign_velvet_friday_event", "campaign_quiet_weekend_extension"],
    badgeText: "Daily Ritual",
    specs: {
      volume: "200 ml",
      texture: "Foaming gel",
      skinFeel: "Soft and refreshed",
    },
    seoTitle: "Silk Mineral Shower Foam | Serein House",
    seoDescription: "A premium foaming shower gel with white fig and mineral water notes.",
  },
  {
    id: "product_moonmilk_bath_soak",
    internalName: "Product: Moonmilk Bath Soak",
    slug: "moonmilk-bath-soak",
    name: "Moonmilk Bath Soak",
    shortDescription: "A mineral soak with oat milk, pale lavender, and cedar vapor.",
    longDescription: richTextParagraphs(
      "Moonmilk Bath Soak dissolves into the bath with a clouded mineral softness that helps shift the body toward evening ease.",
      "The scent remains low and comforting, led by oat milk and pale lavender rather than overt floral sweetness.",
    ),
    price: 38,
    salePrice: 32,
    sku: "SH-BS-202",
    primaryImageId: "asset_product_set_b",
    galleryImageIds: ["asset_product_set_b", "asset_category_bath_shower"],
    categoryId: "category_bath_shower",
    tags: ["bath", "lavender", "soak"],
    audienceSegments: ["relax-and-unwind", "self-care-ritual"],
    featuredCampaignIds: ["campaign_first_light_preview", "campaign_midnight_monday_finale"],
    badgeText: "Evening Essential",
    specs: {
      weight: "500 g",
      texture: "Mineral crystals",
      mood: ["soothing", "quiet", "restorative"],
    },
    seoTitle: "Moonmilk Bath Soak | Serein House",
    seoDescription: "A mineral bath soak with oat milk, pale lavender, and cedar vapor.",
  },
  {
    id: "product_stillwater_body_polish",
    internalName: "Product: Stillwater Body Polish",
    slug: "stillwater-body-polish",
    name: "Stillwater Body Polish",
    shortDescription: "A fine-grain polish that leaves the skin luminous and soft.",
    longDescription: richTextParagraphs(
      "Stillwater pairs fine mineral grains with a creamy oil base to smooth the skin without stripping comfort from the ritual.",
      "The finish is clean, refined, and easy to layer under body creme or hand care.",
    ),
    price: 36,
    salePrice: 30,
    sku: "SH-BS-203",
    primaryImageId: "asset_product_set_b",
    galleryImageIds: ["asset_product_set_b", "asset_category_body_hand"],
    categoryId: "category_bath_shower",
    tags: ["polish", "mineral", "body"],
    audienceSegments: ["self-care-ritual"],
    featuredCampaignIds: ["campaign_velvet_friday_event"],
    badgeText: "Glow Ritual",
    specs: {
      weight: "250 g",
      finish: "Cream-oil polish",
      use: "1-2 times weekly",
    },
    seoTitle: "Stillwater Body Polish | Serein House",
    seoDescription: "A fine-grain body polish for luminous, soft skin.",
  },
  {
    id: "product_amber_oat_body_creme",
    internalName: "Product: Amber Oat Body Creme",
    slug: "amber-oat-body-creme",
    name: "Amber Oat Body Creme",
    shortDescription: "A rich body creme with amber, oat silk, and soft sandalwood.",
    longDescription: richTextParagraphs(
      "Amber Oat was created to feel generous but never heavy. It settles into the skin with a cashmere-soft finish and a warm scent veil that remains close to the body.",
      "Apply after bathing or before evening rest to prolong the feeling of care.",
    ),
    price: 42,
    salePrice: 35,
    sku: "SH-BH-301",
    primaryImageId: "asset_product_set_c",
    galleryImageIds: ["asset_product_set_c", "asset_category_body_hand"],
    categoryId: "category_body_hand_care",
    tags: ["amber", "body creme", "oat"],
    audienceSegments: ["relax-and-unwind", "self-care-ritual"],
    featuredCampaignIds: ["campaign_velvet_friday_event", "campaign_midnight_monday_finale"],
    badgeText: "Customer Favorite",
    specs: {
      volume: "220 ml",
      finish: "Velvet creme",
      suitableFor: ["daily use", "dry skin"],
    },
    seoTitle: "Amber Oat Body Creme | Serein House",
    seoDescription: "A rich body creme with amber, oat silk, and soft sandalwood.",
  },
  {
    id: "product_velvet_citrus_hand_balm",
    internalName: "Product: Velvet Citrus Hand Balm",
    slug: "velvet-citrus-hand-balm",
    name: "Velvet Citrus Hand Balm",
    shortDescription: "A nourishing hand balm with citrus peel, petitgrain, and blond woods.",
    longDescription: richTextParagraphs(
      "Velvet Citrus brings brightness to the hand-care ritual while still feeling soft and grounded. The balm absorbs quickly and leaves a polished finish on the skin.",
      "Keep it at the sink, in a work bag, or inside a guest set for an easy gifting gesture.",
    ),
    price: 22,
    salePrice: 18,
    sku: "SH-BH-302",
    primaryImageId: "asset_product_set_c",
    galleryImageIds: ["asset_product_set_c", "asset_category_body_hand"],
    categoryId: "category_body_hand_care",
    tags: ["hand balm", "citrus", "petitgrain"],
    audienceSegments: ["gifting", "self-care-ritual"],
    featuredCampaignIds: ["campaign_first_light_preview", "campaign_velvet_friday_event"],
    badgeText: "Desk-to-Bag",
    specs: {
      volume: "75 ml",
      finish: "Quick-absorbing balm",
      packaging: "Aluminum tube",
    },
    seoTitle: "Velvet Citrus Hand Balm | Serein House",
    seoDescription: "A nourishing hand balm with citrus peel, petitgrain, and blond woods.",
  },
  {
    id: "product_softwood_hand_wash",
    internalName: "Product: Softwood Hand Wash",
    slug: "softwood-hand-wash",
    name: "Softwood Hand Wash",
    shortDescription: "A gentle hand wash with hinoki, bergamot leaf, and skin-softening glycerin.",
    longDescription: richTextParagraphs(
      "Softwood Hand Wash turns a practical sinkside step into something more composed. The lather is gentle, the finish comfortable, and the scent reads quietly luxurious.",
      "Pair it with the coordinating balm for a refined hand ritual set.",
    ),
    price: 28,
    salePrice: 24,
    sku: "SH-BH-303",
    primaryImageId: "asset_product_set_c",
    galleryImageIds: ["asset_product_set_c", "asset_category_body_hand"],
    categoryId: "category_body_hand_care",
    tags: ["hand wash", "hinoki", "sinkside"],
    audienceSegments: ["gifting", "relax-and-unwind"],
    featuredCampaignIds: ["campaign_velvet_friday_event"],
    badgeText: "Sinkside Pairing",
    specs: {
      volume: "300 ml",
      finish: "Silken wash",
      pump: true,
    },
    seoTitle: "Softwood Hand Wash | Serein House",
    seoDescription: "A gentle hand wash with hinoki, bergamot leaf, and glycerin.",
  },
  {
    id: "product_evening_reset_gift_box",
    internalName: "Product: Evening Reset Gift Box",
    slug: "evening-reset-gift-box",
    name: "Evening Reset Gift Box",
    shortDescription: "A composed evening set with candle, bath soak, and body creme.",
    longDescription: richTextParagraphs(
      "Evening Reset gathers three of our most calming rituals into one polished gift box: Dawn Ember Candle, Moonmilk Bath Soak, and Amber Oat Body Creme.",
      "It is designed for host gifting, thoughtful thank-yous, and self-gifting that feels genuinely generous.",
    ),
    price: 98,
    salePrice: 82,
    sku: "SH-GS-401",
    primaryImageId: "asset_product_set_c",
    galleryImageIds: ["asset_product_set_c", "asset_category_gift_sets"],
    categoryId: "category_gift_sets",
    tags: ["gift box", "evening", "best seller"],
    audienceSegments: ["gifting", "relax-and-unwind"],
    featuredCampaignIds: [
      "campaign_first_light_preview",
      "campaign_velvet_friday_event",
      "campaign_quiet_weekend_extension",
    ],
    badgeText: "Limited Box",
    specs: {
      contents: ["Dawn Ember Candle", "Moonmilk Bath Soak", "Amber Oat Body Creme"],
      packaging: "Rigid presentation box",
      wrapIncluded: true,
    },
    seoTitle: "Evening Reset Gift Box | Serein House",
    seoDescription: "A premium evening gift set with candle, bath soak, and body creme.",
    draftOverrides: {
      salePrice: 78,
      badgeText: "Preview Offer",
    },
  },
  {
    id: "product_winter_hearth_collection",
    internalName: "Product: Winter Hearth Collection",
    slug: "winter-hearth-collection",
    name: "Winter Hearth Collection",
    shortDescription: "A seasonal trio with candle, diffuser, and room mist in warm woods.",
    longDescription: richTextParagraphs(
      "Winter Hearth Collection layers the home with amber woods and softened spice through three complementary formats built for hosting season.",
      "It creates an immediate sense of occasion while remaining understated enough for daily living.",
    ),
    price: 124,
    salePrice: 104,
    sku: "SH-GS-402",
    primaryImageId: "asset_product_set_a",
    galleryImageIds: ["asset_product_set_a", "asset_category_gift_sets"],
    categoryId: "category_gift_sets",
    tags: ["seasonal", "gift set", "home fragrance"],
    audienceSegments: ["gifting"],
    featuredCampaignIds: ["campaign_velvet_friday_event", "campaign_midnight_monday_finale"],
    badgeText: "Holiday Edit",
    specs: {
      contents: ["Dawn Ember Candle", "Quiet Cedar Diffuser", "Neroli Veil Room Mist"],
      packaging: "Seasonal gift box",
      wrapIncluded: true,
    },
    seoTitle: "Winter Hearth Collection | Serein House",
    seoDescription: "A premium seasonal trio with candle, diffuser, and room mist.",
  },
  {
    id: "product_renewal_hand_ritual_duo",
    internalName: "Product: Renewal Hand Ritual Duo",
    slug: "renewal-hand-ritual-duo",
    name: "Renewal Hand Ritual Duo",
    shortDescription: "A hand wash and balm pairing for polished daily gifting.",
    longDescription: richTextParagraphs(
      "Renewal Hand Ritual Duo brings together Softwood Hand Wash and Velvet Citrus Hand Balm for a sinkside ritual that feels elevated from the first use.",
      "It is one of our easiest gifts to send and one of our easiest sets to keep for yourself.",
    ),
    price: 46,
    salePrice: 39,
    sku: "SH-GS-403",
    primaryImageId: "asset_product_set_c",
    galleryImageIds: ["asset_product_set_c", "asset_category_gift_sets"],
    categoryId: "category_gift_sets",
    tags: ["duo", "hand care", "giftable"],
    audienceSegments: ["gifting"],
    featuredCampaignIds: ["campaign_first_light_preview", "campaign_velvet_friday_event"],
    badgeText: "Easy Gift",
    specs: {
      contents: ["Softwood Hand Wash", "Velvet Citrus Hand Balm"],
      suitableFor: ["host gifts", "desk gifts", "guest rooms"],
    },
    seoTitle: "Renewal Hand Ritual Duo | Serein House",
    seoDescription: "A premium hand wash and balm gift set.",
  },
  {
    id: "product_serein_sleep_stone_set",
    internalName: "Product: Serein Sleep Stone Set",
    slug: "serein-sleep-stone-set",
    name: "Serein Sleep Stone Set",
    shortDescription: "A bedside rest set with warming stone, eye pillow, and mist cloth.",
    longDescription: richTextParagraphs(
      "Serein Sleep Stone Set is a small ritual toolkit for signaling the end of the day. It pairs tactile comfort with a minimalist bedside presence.",
      "Use the warming stone in the hands, the eye pillow in rest, and the mist cloth with room spray for a slower transition into night.",
    ),
    price: 64,
    salePrice: 54,
    sku: "SH-WA-501",
    primaryImageId: "asset_product_set_d",
    galleryImageIds: ["asset_product_set_d", "asset_category_wellness_accessories"],
    categoryId: "category_wellness_accessories",
    tags: ["sleep", "accessory", "bedside"],
    audienceSegments: ["relax-and-unwind", "self-care-ritual"],
    featuredCampaignIds: ["campaign_first_light_preview", "campaign_midnight_monday_finale"],
    badgeText: "New Arrival",
    specs: {
      contents: ["Basalt warming stone", "linen eye pillow", "mist cloth"],
      use: "Evening ritual",
      packaging: "Drawstring cotton pouch",
    },
    seoTitle: "Serein Sleep Stone Set | Serein House",
    seoDescription: "A bedside wellness accessory set for slower evenings and better rest.",
  },
];

export const campaignSeeds: SeedCampaign[] = [
  {
    id: "campaign_first_light_preview",
    internalName: "Campaign: First Light Preview",
    slug: "first-light-preview",
    campaignType: "teaser",
    startDate: "2026-11-16T00:00:00.000Z",
    endDate: "2026-11-26T23:59:59.000Z",
    headline: "First Light Preview",
    subheadline:
      "A calm beginning to the season with early access sets, layered fragrance, and editorial gifting inspiration.",
    statusLabel: "Preview Open",
    activeAudienceSegments: ["gifting", "relax-and-unwind"],
    heroBannerId: "hero_campaign_teaser",
    promoStripIds: ["promo_teaser_all"],
    featuredProductIds: [
      "product_evening_reset_gift_box",
      "product_renewal_hand_ritual_duo",
      "product_dawn_ember_candle",
      "product_serein_sleep_stone_set",
    ],
    featuredCategoryIds: ["category_gift_sets", "category_home_fragrance"],
    published: true,
  },
  {
    id: "campaign_velvet_friday_event",
    internalName: "Campaign: Velvet Friday Event",
    slug: "velvet-friday-event",
    campaignType: "black-friday",
    startDate: "2026-11-27T00:00:00.000Z",
    endDate: "2026-11-27T23:59:59.000Z",
    headline: "Velvet Friday Event",
    subheadline:
      "The main event brings together our most giftable home, bath, and body rituals in one polished seasonal release.",
    statusLabel: "Now Live",
    activeAudienceSegments: ["gifting", "relax-and-unwind", "self-care-ritual"],
    heroBannerId: "hero_campaign_black_friday",
    promoStripIds: ["promo_bf_gifting", "promo_bf_relax"],
    featuredProductIds: [
      "product_evening_reset_gift_box",
      "product_winter_hearth_collection",
      "product_amber_oat_body_creme",
      "product_silk_mineral_shower_foam",
    ],
    featuredCategoryIds: [
      "category_gift_sets",
      "category_body_hand_care",
      "category_home_fragrance",
    ],
    published: true,
  },
  {
    id: "campaign_quiet_weekend_extension",
    internalName: "Campaign: Quiet Weekend Extension",
    slug: "quiet-weekend-extension",
    campaignType: "weekend",
    startDate: "2026-11-28T00:00:00.000Z",
    endDate: "2026-11-29T23:59:59.000Z",
    headline: "Quiet Weekend Extension",
    subheadline:
      "A softer continuation of the event with select favorites still available while stock remains.",
    statusLabel: "Extended",
    activeAudienceSegments: ["relax-and-unwind", "self-care-ritual"],
    heroBannerId: "hero_campaign_weekend",
    promoStripIds: ["promo_weekend_all"],
    featuredProductIds: [
      "product_quiet_cedar_diffuser",
      "product_silk_mineral_shower_foam",
      "product_evening_reset_gift_box",
      "product_serein_sleep_stone_set",
    ],
    featuredCategoryIds: [
      "category_home_fragrance",
      "category_bath_shower",
      "category_wellness_accessories",
    ],
    published: false,
  },
  {
    id: "campaign_midnight_monday_finale",
    internalName: "Campaign: Midnight Monday Finale",
    slug: "midnight-monday-finale",
    campaignType: "cyber-monday",
    startDate: "2026-11-30T00:00:00.000Z",
    endDate: "2026-11-30T23:59:59.000Z",
    headline: "Midnight Monday Finale",
    subheadline:
      "The season closes online with a distilled final edit of modern home fragrance and evening-care essentials.",
    statusLabel: "Final Hours",
    activeAudienceSegments: ["gifting", "self-care-ritual"],
    heroBannerId: "hero_campaign_cyber_monday",
    promoStripIds: ["promo_cyber_all"],
    featuredProductIds: [
      "product_serein_sleep_stone_set",
      "product_amber_oat_body_creme",
      "product_neroli_veil_room_mist",
      "product_winter_hearth_collection",
    ],
    featuredCategoryIds: [
      "category_wellness_accessories",
      "category_home_fragrance",
      "category_gift_sets",
    ],
    published: false,
  },
];
